### ISSUE TITLE
Привет!

### ISSUE THREAD

**Issue by Gasug** [xKARASb/SferumBot#10]
Я бы очень хотел узнать побольше о том как ты посылаешь get и post запросы. Почему именно эти параметры? Где взять документацию?

**Comment by R1senDev** [comment]
Официальной документации для всяких Сферумовских API нет, однако можно захватывать свои же запросы для дальнейшего анализа. Полагаю, так и зделал автор репозитория, это моё предположение.

**Comment by xKARASb** [comment]
> Я бы очень хотел узнать побольше о том как ты посылаешь get и post запросы. Почему именно эти параметры? Где взять документацию?
Привет, вся API изучалась методом бесконечных тестов, анализа работы самого сайта. Я просто брал запросы, которые исходили и изучал их. Так же, часть запросов можно посмотреть у VK api, но там есть некоторые важные отличия. Если нужна будет помощь, можешь обращаться мне в ТГ
