### ISSUE TITLE
Ребзя, проект заброшен? В данный момент не работает

### ISSUE THREAD

**Issue by Belekov-Aden** [xKARASb/SferumBot#9]
win 11
Microsoft Edge
ru

**Comment by Microvolna** [comment]
Добрый вечер, у меня все работает! Возможно инcтрукция показалась непонятной, попытаюсь обяснить:

1. Клонируем репозиторий:

```
git clone https://github.com/xKARASb/SferumBot
cd SferumBot
```

2. Устанавливаем необходимые зависимости:

```
pip install -r requirements.txt
```

3. Заполняем `.env`:

- `AUTH_COOKIE`

Переходим в [Sferum](https://web.vk.me/)

Нажимаем <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd>, после чего откроются параметры для разработчиков.

На открывшейся панели нажимаем на плюсик (см. прикрепленный скриншот).

![image](https://github.com/user-attachments/assets/8779a327-dedc-4ecc-a37d-a80804510631)

В открывшейся панельке выбираем "Приложение".

Затем заходим в раздел "Файлы cookie" > "https://web.vk.me" (см. прикрепленный скришот)

![image](https://github.com/user-attachments/assets/ea309467-56e1-4e11-90d8-9f1616f0f292)

Сверху нажимаем на "Фильтр" и вводим "remixdsid" (см. прикрепленный скриншот)

![image](https://github.com/user-attachments/assets/9bc4953b-fded-43d0-80ba-7829490a258d)

Копируем значение (должно начинаться с "vk1.a.") и записываем его в файл "example.env"

- `BOT_TOKEN`

Создадим бота, который будет присылать нам уведомления:

Переходим в [BotFather](https://t.me/BotFather).

Вводим комманду `/newbot`, после чего нужно будет ввести отображаемое имя бота (любые символы), после чего username бота (символы только английского алфавита, должно оканчиваться на "_bot")

После чего он отправит вам токен бота (см. прикрепленный скриншот)

![image](https://github.com/user-attachments/assets/742605b8-a20d-43f3-8e73-660d096a0519)

Заносим токен в "example.env".

- `TG_USER_ID`

Переходим в [бота](https://t.me/my_id_bot) и компируем свой id (см. прикрепленный скриншот).

![image](https://github.com/user-attachments/assets/709d9905-479e-4169-96aa-aa652d18b5ee)

Записываем его в "example.env".

- `TG_CHAT_ID`

Этот параметр отвечает за чат, в который будут отправляться сообщения из сферума, если вы хотите, чтобы бот отправлял вам в лично - продублируйте id из прошлого шага. Можно идти к следующему шагу.

В ином случае перешлите любой сообщение из группы/канала [боту](https://t.me/my_id_bot) и запишите полученный в боте id в поле.

**ВНИМАНИЕ!!! Нужно добавить бота в администраторы канала,группы.**

- `VK_CHAT_ID`

Id чата (-ов) из которого (-ых) будут пересылаться сообщения:

Откройте любой чат в сферуме и скопируйте id из ссылки, id чата выглядит примерно так 624767396. (см. прикрепленный скриншот)

![image](https://github.com/user-attachments/assets/d64bd1b4-97d8-4872-9194-846770162c0d)

4. Переименовать `example.env` в `.env`

5. Запускаем бота:

```
python startup.py
```

или просто открыть `startup.py`

**Comment by xKARASb** [comment]
Отличное объяснение, спасибо!
